config/routes.rb
Rails.application.routes.draw do
  resources :registrations
  resources :social_posts, only: [:index, :create]
  resources :static_pages
  root to: 'static_pages#home'
  post '/contact', to: 'static_pages#contact', as: 'contact'
  devise_for :users
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  has_many :registration_members, dependent: :destroy
  accepts_nested_attributes_for :registration_members, allow_destroy: true
  alias members registration_members

  validates :name, presence: true
  validates :stripe_customer_id, presence: true
  validates :stripe_charge_id, presence: true

  def members_list
    self.registration_members.map { |member| "#{member.name} | #{member.shirt_size}" }
  end
end

app/models/registration_member.rb
class RegistrationMember < ActiveRecord::Base
  belongs_to :registration

  validates :name, presence: true
  validates :email, presence: true
end

app/models/social_post.rb
class SocialPost < ActiveRecord::Base
  validates :service_id, uniqueness: { scope: :service }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_registration, only: [:show, :edit, :update, :destroy]
  layout 'registrations'

  # GET /registrations
  # GET /registrations.json
  def index
    @registrations = Registration.all
  end

  # GET /registrations/1
  # GET /registrations/1.json
  def show
  end

  # GET /registrations/new
  def new
    redirect_to root_path, notice: 'Registration is Closed at this time.'
    # @type = params[:type]
    # @registration = Registration.new(subtype: params[:type])
    #
    # if @type == 'team'
    #   2.times do @registration.registration_members.build end
    # end
  end

  # GET /registrations/1/edit
  def edit
    @type = @registration.subtype
  end

  # POST /registrations
  # POST /registrations.json
  def create
    @registration = Registration.new(registration_params)

    # Amount in cents
    @amount = @registration.subtype == 'team' ? 9000 : 5000

    # Disabled for now,
    # customer = Stripe::Customer.create(
    #   :email => params[:stripeEmail],
    #   :source  => params[:stripeToken]
    # )
    #
    # charge = Stripe::Charge.create(
    #   :customer    => customer.id,
    #   :amount      => @amount,
    #   :description => 'EnergyX Resolve To Row',
    #   :currency    => 'usd'
    # )
    #
    # @registration.is_paid = true if customer && charge
    # @registration.stripe_customer_id = customer.id
    # @registration.stripe_charge_id = charge.id

    respond_to do |format|
      if @registration.save
        format.html { redirect_to @registration, notice: 'We have successfully created your registration! You card HAS NOT BEEN CHARGED. Please Print this page for your records.' }
        format.json { render :show, status: :created, location: @registration }
      else
        format.html { render :new }
        format.json { render json: @registration.errors, status: :unprocessable_entity }
      end
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_registration_path(@registration)
  end

  # PATCH/PUT /registrations/1
  # PATCH/PUT /registrations/1.json
  def update
    respond_to do |format|
      if @registration.update(registration_params)
        format.html { redirect_to @registration, notice: 'Registration was successfully updated.' }
        format.json { render :show, status: :ok, location: @registration }
      else
        format.html { render :edit }
        format.json { render json: @registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registrations/1
  # DELETE /registrations/1.json
  def destroy
    @registration.destroy
    respond_to do |format|
      format.html { redirect_to registrations_url, notice: 'Registration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registration
      @registration = Registration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registration_params
      params.require(:registration).permit(:is_paid, :shirt_size, :name, :subtype, :phone, :email, registration_members_attributes: [:id, :name, :email, :phone, :_destroy, :shirt_size])
    end
end

app/controllers/social_posts_controller.rb
class SocialPostsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
    if params['hub.mode'] == 'subscribe'
      render text: params['hub.challenge']
    else
      render text: 'No challenge parameter sent.'
    end
  end

  def create
    begin
      Instagram.process_subscription(request.body) do |handler|
        handler.on_user_changed do |user_id, data|
          client = Instagram.client(access_token: ENV['INSTAGRAM_TOKEN'])
          post = client.media_item(data['data']['media_id'])
          SocialPost.create!(
            service: 'instagram',
            service_id: post['id'],
            link: post['link'],
            oembed: HTTParty.get("https://api.instagram.com/oembed?url=#{post['link']}&omitscript=true")['html']
          )
          render text: "user_id: #{user_id} media_id: #{data['data']['media_id']}"
        end
      end
    rescue
      render text: 'looks like there is something wrong with your request...'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    #@posts = SocialPost.order('created_at DESC').limit(4)
    client = Instagram.client(access_token: ENV['INSTAGRAM_TOKEN'])
    @posts = client.user_recent_media.first(4).map do |post|
      HTTParty.get("https://api.instagram.com/oembed?url=#{post['link']}&omitscript=true")['html']
    end rescue []

  end

  def contact
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    @spam_check = params[:spam_check]

    unless @spam_check = 'gotcha.'
      flash[:alert] = 'We think this might be spam... Call us if you disagree!'
      redirect_to root_path and return
    end

    if @name.blank?
      flash[:danger] = 'Please enter your name before sending your message. Thank you.'
      redirect_to root_path
    elsif @email.blank? || @email.scan(/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i).size < 1
      flash[:danger] = 'You must provide a valid email address before sending your message. Thank you.'
      redirect_to root_path
    elsif @message.blank? || @message.length < 10
      flash[:danger] = 'Your message is empty. Requires at least 10 characters. Nothing to send.'
      redirect_to root_path
    elsif @message.scan(/<a href=/).size > 0 || @message.scan(/\[url=/).size > 0 || @message.scan(/\[link=/).size > 0 || @message.scan(/http:\/\//).size > 0
      flash[:danger] = "Please don't include links. Spammers do this. Thank you for your understanding."
      redirect_to root_path
    else
      ContactMailer.contact_message(@name, @email, @message).deliver
      flash[:success] = 'Your message was sent! We will get back to you shortly.'
      if @message == 'Intersted in a free class!'
        redirect_to 'https://clients.mindbodyonline.com/classic/home?studioid=226360'
      else
        redirect_to root_path
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def self.line_break(s)
    s.gsub("\n", '<br/>')
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/social_posts_helper.rb
module SocialPostsHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/application.html.haml
!!!
%html
  %head
    = favicon_link_tag 'favicon.png', rel: 'favicon', type: 'image/png'
    = favicon_link_tag 'energyx_apple_touch_icon.png', rel: 'apple-touch-icon', type: 'image/png'
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : 'EnergyX Fitness | San Antonio Fitness Classes'
    %meta{:content => "#{content_for?(:description) ? yield(:description) : "San Antonio’s first rowing studio featuring ShockWave, IndoRow, TRX and Yoga. We offer a wide variety of classes available to any age and any fitness level sure to target your fitness needs."}", :name => "description"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{id: "#{controller_name}_#{action_name}", class: "#{controller_name}"}
    = render 'shared/header'
    = render 'layouts/messages'
    = yield
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-76055700-1', 'auto');
    ga('send', 'pageview');
  %script{:async => "", :defer => '', :src => "http://platform.instagram.com/en_US/embeds.js"}
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-77252693-44', 'auto');
    ga('send', 'pageview');
  %footer.footer
    .container.footer-text
      = render 'shared/footer'

app/views/layouts/registrations.html.haml
!!!
%html
  %head
    = favicon_link_tag 'favicon.png', rel: 'favicon', type: 'image/png'
    = favicon_link_tag 'energyx_apple_touch_icon.png', rel: 'apple-touch-icon', type: 'image/png'
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : 'EnergyX Fitness | San Antonio Fitness Classes'
    %meta{:content => "#{content_for?(:description) ? yield(:description) : "San Antonio’s first rowing studio featuring ShockWave, IndoRow, TRX and Yoga. We offer a wide variety of classes available to any age and any fitness level sure to target your fitness needs."}", :name => "description"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{id: "#{controller_name}_#{action_name}", class: "#{controller_name}"}
    = render 'shared/header'
    .container{style: 'margin-top: 100px'}
      .row
        .col-sm-6.col-centered
          = render 'layouts/messages'
      = yield
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-76055700-1', 'auto');
    ga('send', 'pageview');
  %script{:async => "", :defer => '', :src => "http://platform.instagram.com/en_US/embeds.js"}
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-77252693-44', 'auto');
    ga('send', 'pageview');
  %footer.footer
    .container.footer-text
      = render 'shared/footer'

app/views/shared/_footer.html.haml
%hr
.row
  .col-xs-6.col-sm-6.col-md-6.col-lg-6
    .pull-left
      %i.fa.fa-copyright
      EnergyX Fitness, LLC
  .col-xs-6.col-sm-6.col-md-6.col-lg-6
    .pull-right
      %ul.social-media
        %li.phone
          %a{href: 'tel:+12106084241', class: 'nav-link'}
            %i.fa.fa-phone
        %li.map
          %a{href: "https://www.google.com/maps/place/EnergyX+Fitness/@29.47474,-98.4647583,17z/data=!4m7!1m4!3m3!1s0x865cf57535c2e3ad:0x51ff463e06dd0672!2s5162+Broadway+St,+Alamo+Heights,+TX+78209!3b1!3m1!1s0x865cf57535c6460d:0x664a0a07536afd98", class: 'nav-link'}
            %i.fa.fa-map-o
        %li.facebook
          %a{href: "https://www.facebook.com/EnergyX-Fitness-1060284187320786/", class: 'nav-link'}
            %i.fa.fa-facebook
        %li.twitter
          %a{href: "https://twitter.com/EnergyxFitness", class: 'nav-link'}
            %i.fa.fa-twitter
        %li.instagram
          %a{href: "https://www.instagram.com/energyxfitness/", class: 'nav-link'}
            %i.fa.fa-instagram

:javascript
  /*  */
  var google_conversion_id = 875970052;
  var google_custom_params = window.google_tag_params;
  var google_remarketing_only = true;
  /*  */
%script{:src => "//www.googleadservices.com/pagead/conversion.js", :type => "text/javascript"}
%noscript
  %div{:style => "display:inline;"}
    %img{:alt => "", :height => "1", :src => "//googleads.g.doubleclick.net/pagead/viewthroughconversion/875970052/?value=0&guid=ON&script=0", :style => "border-style:none;", :width => "1"}/

app/views/shared/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#navbar-brand-centered", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar{style: 'background-color: white;'}
        %span.icon-bar{style: 'background-color: white;'}
        %span.icon-bar{style: 'background-color: white;'}
      .navbar-brand.navbar-brand-centered
        %a{href: root_path}
          %img#NavLogo{:src => asset_url('energyx_icon_white.png')}
          %div{:style => "clear:both;"}
    / Collect the nav links, forms, and other content for toggling
    #navbar-brand-centered.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-left
        %li
          %a{href: 'tel:+12106084241', class: 'nav-link'}
            %i.fa.fa-phone
        %li.text-white
          %a{href: "https://www.google.com/maps/place/EnergyX+Fitness/@29.47474,-98.4647583,17z/data=!4m7!1m4!3m3!1s0x865cf57535c2e3ad:0x51ff463e06dd0672!2s5162+Broadway+St,+Alamo+Heights,+TX+78209!3b1!3m1!1s0x865cf57535c6460d:0x664a0a07536afd98", class: 'nav-link'}
            %i.fa.fa-map-marker
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "http://www.energyxfitness.com#Schedule"} Schedule
        %li
          %a{:href => "http://www.energyxfitness.com#Results"} Results
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            About
            %b.caret
          %ul.dropdown-menu
            %li
              %a{:href => "http://www.energyxfitness.com#Faq"} FAQs
            %li
              %a{:href => "http://www.energyxfitness.com#Coaches"} Coaches
            %li
              %a{:href => "http://www.energyxfitness.com#Memberships"} Memberships
    / /.navbar-collapse
  / /.container-fluid

app/views/shared/_tools.html.haml
%section#Tools
  .container
    .row
      .col-xs-12.col-sm-6.col-md-4.col-lg-4
        .pull-right
          .panel.panel-success#CallOutPanel
            .panel-body
              %h2
                Your first class is
                = succeed "" do
                  %strong.text-success free.
              %p Our dynamic classes will leave you feeling fit, empowered, and ready to achieve your goals. Try your first one for FREE today!
              = form_tag contact_path, method: 'post', html: {role: "form"} do
                .form-group
                  = text_field_tag :name, @name, placeholder: "Enter your name...", class: "form-control"
                .form-group
                  = text_field_tag :email, @email, placeholder: "Enter your email...", class: "form-control"
                .form-group
                  = hidden_field_tag :message, @message, value: 'Intersted in a free class!'
                  = hidden_field_tag 'spam_check', value: 'gotcha.'
                .pull-right
                  %button.btn.btn-success.btn-lg{type: "submit"} Send

app/views/static_pages/jobs.html.haml
%h1 Jobs

app/views/visitors/index.html.haml
%body
  %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
    .container
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"} Start Bootstrap
      / Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li
            %a{:href => "#about"} About
          %li
            %a{:href => "#services"} Services
          %li
            %a{:href => "#contact"} Contact
      / /.navbar-collapse
    / /.container
  / Full Width Image Header
  %header.header-image
    .headline
      .container
        %h1 One Page Wonder
        %h2 Will Knock Your Socks Off
  / Page Content
  .container
    %hr.featurette-divider/
    / First Featurette
    #about.featurette
      %img.featurette-image.img-circle.img-responsive.pull-right{:src => "http://placehold.it/500x500"}/
      %h2.featurette-heading
        This First Heading
        %span.text-muted Will Catch Your Eye
      %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
    %hr.featurette-divider/
    / Second Featurette
    #services.featurette
      %img.featurette-image.img-circle.img-responsive.pull-left{:src => "http://placehold.it/500x500"}/
      %h2.featurette-heading
        The Second Heading
        %span.text-muted Is Pretty Cool Too.
      %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
    %hr.featurette-divider/
    / Third Featurette
    #contact.featurette
      %img.featurette-image.img-circle.img-responsive.pull-right{:src => "http://placehold.it/500x500"}/
      %h2.featurette-heading
        The Third Heading
        %span.text-muted Will Seal the Deal.
      %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
    %hr.featurette-divider/
    / Footer
    %footer
      .row
        .col-lg-12
          %p Copyright © Your Website 2014
  / /.container